### ISSUE TITLE
Question: How to plug in "external" ueransim?

### ISSUE THREAD

**Issue by 0x41gawor** [niloysh/open5gs-k8s#7]
Hi,

First, I want to express my great appreciation for this amazing repository. The project is truly impressive!

I would like to ask if it is possible to connect an external `nr-gnb` to the core network. By "external," I mean running the nr-gnb binary directly on the host machine, outside the Kubernetes cluster.

What considerations should I take into account when doing this?
I understand that I need to expose some services outside the k8s cluster, such as the AMF. How should I connect to the N2 and N3 networks?

I have tried changing the amf-namf service type to NodePort, but this alone does not allow me to establish an SCTP session. The `nr-gnb` logs indicate that the network is unreachable. Do you have any idea what might be causing this issue?

I would be very grateful for your response! :D

**Comment by niloysh** [comment]
Hi Andrzej,
Sorry for the delayed response, I’m glad you figured it out.
Usually, I add an IP to the bridge and then bind UERANSIM or other gNB to that IP address, and that works.

I’ll add it to the readme when I find the time.

Best,
Niloy

From: Andrzej Gawor ***@***.***>
Date: Tuesday, December 17, 2024 at 3:55 PM
To: niloysh/open5gs-k8s ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [niloysh/open5gs-k8s] Question: How to plug in "external" ueransim? (Issue #7)

Ok, I did it. If someone would be interested in my solution feel free to contact me :D

**Comment by kamelferrahi** [comment]
Hi Andrzej , I would like to know how did you manage to deploy the gnb outside the cluster and make it work.
